services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: iris
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
