[project]
name = "deng-task"
version = "0.1.0"
description = "Data engineering test task"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "psycopg>=3.2.9",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
